events:
  export:
    graphite:
      enabled: false
      min-level: TRACE
      host: localhost
      port: 2004
      protocol: pickle
      batch-size: 100
      linger-period: 10s
      publishers: 2
      prefix: qalipsis.

meters:
  export:
    graphite:
      enabled: false
      host: localhost
      port: 2004
      protocol: pickle
      batch-size: 100
      prefix: qalipsis.
      publishers: 1

