micronaut:
  application:
    name: qalipsisPluginGraphite
metrics:
  graphite:
    enabled: true
    host: localhost
    port: 2004
    protocol: pickle
    batch-size: 2
    batch-flush-interval-seconds: 10
