events:
  export:
    graphite:
      enabled: true
      min-level: INFO
      host: localhost
      port: 2004
      protocol: pickle
      batch-size: 2
      linger-period: 10s
      publishers: 2

# Disables the native micronaut registry.
micronaut.metrics.export.graphite.enabled: false

meters:
  export:
    graphite:
      host: localhost
      port: 2004
      enabled: false
      step: PT10S

